language: cpp

os:
        - linux
        - macos
        - windows

compiler:
        - gcc
        - clang
        - Visual Studio

       
script:
        - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install python        ; fi
        - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install pip           ; fi
        - if [ "$TRAVIS_OS_NAME" == "windows" ]; pip3.exe install --user conan    ; fi
        - pip install --user conan
        - conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"
        - mkdir build && cd build
        - conan install .. --build missing && cmake .. && cmake --build .

notifications:
        email:
                recipients:
                        - ccna.syl@gmail.com
                on_success: change
                on_failure: change                     
