language:
        - python
        - c++
os:
        - linux
        - macos

compiler:
        - gcc
        - clang

install:
        - pip install conan
        - conan user
        - conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"

script:
        - mkdir build && cd build
        - conan install .. --build missing && cmake .. && cmake --build .

notifications:
        email:
                recipients:
                        - ccna.syl@gmail.com
                on_success: change
                on_failure: change                     
